### ISSUE TITLE
第一回棚卸し : フィードバック

### ISSUE THREAD

**Issue by denari** [kosen10s/channel-tanaoroshi#2]
下記のようにchannelを棚卸しします。
消すchannelにチェック入れた。
フィードバックはslackの #tanaoroshi01 channelか、できればgithubのissueにコメントを追加してほしい。
- [x] api-test
- [ ] blog
- [x] book
- [ ] bouldering -> sports channelに変更
- [x] cooking
- [ ] currymeshi
- [x] data-science
- [x] design
- [ ] education
- [ ] emoji
- [ ] english-chat
- [x] event
- [x] excursion-disney -> やるならもう一回channelつくれ
- [x] game-tech
- [ ] general
- [ ] gif
- [x] hardware
- [ ] hubot -> botと改名
- [x] inputdevices
- [ ] jisaku-pc -> なんか名前変えてhardwareと一緒くたにしていいんじゃない??
- [ ] koibana
- [x] lt05
- [ ] lt06
- [ ] mashup_awards
- [ ] miku
- [ ] music
- [x] network
- [x] notification
- [ ] officialsite -> denariのわがままでcloseしない。とっととやる。
- [ ] ogiri
- [ ] photo
- [ ] python
- [ ] random
- [ ] ruby
- [ ] smartphones
- [x] software
- [ ] subcul
- [x] tools
- [ ] tsurami-dustbox
- [x] twitter -> private channel化したい。ってかはやくhubotからツイートできるようにしなきゃ
- [ ] very-cute-girl-3
- [ ] web-tech
## 
- tech channelを開設

**Comment by arayaryoma** [comment]
GitHubてチェックボックスのチェック固定できないんだっけ？誤クリック起こりそう

**Comment by denari** [comment]
リポジトリ内のファイルだったらチェック固定できたりして

**Comment by arayaryoma** [comment]
READMEにコピーしてみた

**Comment by ysakasin** [comment]
第一回棚卸しを決行しました

**Comment by unasuke** [comment]
lockしたらcheckboxの固定できるかなって試したけどそんなことなかった
